[python]
symbol = "ğŸ"
format = '$symbol $virtualenv '

[git_status]
disabled = true

[nodejs]
disabled= true

[cmd_duration]
min_time = 10000  # show only if longer than 10s
format = " â± $duration"

[directory]
truncation_length = 5
truncate_to_repo = false
home_symbol = "~"
read_only = " ï€£"

[character]
success_symbol = "[â¯](bold)"
error_symbol = "[â¯](bold)"
