add_newline = false
command_timeout = 1000

# ANSI colors
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$cmd_duration\
$character
"""

[python]
style="fg:green"
symbol = "ğŸ"
format = '$symbol $virtualenv '

[git_status]
disabled = true

[git_branch]
style = "fg:magenta"
format = "[$symbol$branch]($style) "

[nodejs]
disabled= true

[cmd_duration]
min_time = 10000  # show only if longer than 10s
format = " â± $duration"

[directory]
truncation_length = 5
truncate_to_repo = false
home_symbol = "~"
read_only = " ï€£"

[character]
success_symbol = "[â¯](bold)"
error_symbol = "[â¯](bold)"

[conda]
symbol = "ğŸ…’ "
format = "[$symbol$environment]($style) "
style = "bold green"
ignore_base = false
